// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  /// True after `flutterfire configure` wrote real project keys.
  static bool get isConfigured =>
      !android.apiKey.startsWith('YOUR_') && !android.appId.startsWith('YOUR_');

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnYFyl1JLL2TY_zM0-msWj5Q_tlbNNIT0',
    appId: '1:500127525462:web:7a556313230952d858a9f7',
    messagingSenderId: '500127525462',
    projectId: 'quikgarage-fb57c',
    authDomain: 'quikgarage-fb57c.firebaseapp.com',
    storageBucket: 'quikgarage-fb57c.firebasestorage.app',
    measurementId: 'G-GSC8XMREC5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnr_VpiP_tXuT7PQqlY7w3pnonO3zcUSU',
    appId: '1:500127525462:android:def7ed0ee6e73a3a58a9f7',
    messagingSenderId: '500127525462',
    projectId: 'quikgarage-fb57c',
    storageBucket: 'quikgarage-fb57c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNZxko3_ZacUH4wC1e4d0DZZwiikmA994',
    appId: '1:500127525462:ios:f38af097c7e47d0458a9f7',
    messagingSenderId: '500127525462',
    projectId: 'quikgarage-fb57c',
    storageBucket: 'quikgarage-fb57c.firebasestorage.app',
    iosBundleId: 'com.quikgarage.quikgarage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNZxko3_ZacUH4wC1e4d0DZZwiikmA994',
    appId: '1:500127525462:ios:f38af097c7e47d0458a9f7',
    messagingSenderId: '500127525462',
    projectId: 'quikgarage-fb57c',
    storageBucket: 'quikgarage-fb57c.firebasestorage.app',
    iosBundleId: 'com.quikgarage.quikgarage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnYFyl1JLL2TY_zM0-msWj5Q_tlbNNIT0',
    appId: '1:500127525462:web:cd19f6dcdc7ee4fe58a9f7',
    messagingSenderId: '500127525462',
    projectId: 'quikgarage-fb57c',
    authDomain: 'quikgarage-fb57c.firebaseapp.com',
    storageBucket: 'quikgarage-fb57c.firebasestorage.app',
    measurementId: 'G-65DNJ6ZLKV',
  );
}
